[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]
# num = "0.4"
# image = "0.23"
# crossbeam = "0.8"

[dependencies]
image = "0.24.5"
num-complex = "0.3.0"

